server:
  port: 80
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/mockup?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    removeAbandoned: false
    removeAbandonedTimeout: 1000
    logAbandoned: false
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 0
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
    keepAlive: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 等待来自池的连接的最大毫秒数,如果小于250毫秒，则被重置回30秒
      connection-timeout: 30000
      driver-class-name: ${spring.datasource.driverClassName}
    #  控制从池返回的连接的默认事务隔离级别
  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
